version: 1.0
jobs:
  install_app_a:
    name: app_a
    latest_json_url: https://s3-ap-northeast-1.amazonaws.com/lemon-sour-example/app_a/latest.json
    is_archive: false
    output_path: C:\lemon-sour\app_a
    events:
      checking_for_update:
        steps:
          - run:
              name: Nodejs Version
              command: node --version
      update_not_available:
        steps:
          - run:
              name: Nodejs Version
              command: node --version
      update_available:
      download_progress:
      update_downloaded:
      error:

workflows:
  main:
    jobs:
      - install_app_a
