version: 1.0
jobs:
  install_app_a:
    name: app_a
    latest_json_url: http://localhost:3000/app_two-app_no_archive/latest.json
    is_archive: false
    output_path: C:/lemon-sour/app_two-app_no_archive
    events:
      checking_for_update:
      update_not_available:
      update_available:
      download_progress:
      update_downloaded:
        steps:
          - run:
              name: Nodejs Version
              command: node --version
          - run:
              name: boot text file
              command: tail C:\lemon-sour\app_two-app_no_archive\app_a.txt
      error:
  install_app_b:
    name: app_b
    latest_json_url: http://localhost:3000/app_two-app_no_archive/latest.json
    is_archive: false
    output_path: C:/lemon-sour/app_two-app_no_archive
    events:
      checking_for_update:
      update_not_available:
      update_available:
      download_progress:
      update_downloaded:
        steps:
          - run:
              name: boot text file
              command: tail C:/lemon-sour/app_two-app_no_archive/app_b.txt
              sync: true
      error:

workflows:
  main:
    jobs:
      - install_app_b
      - install_app_a
